//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examinations
    {
        public int Id { get; set; }
        public int PatientDieseaseId { get; set; }
        public int ExaminationType { get; set; }
        public int LogType { get; set; }
        public string Comment { get; set; }
        public System.DateTime WhenExamined { get; set; }
    
        public virtual PatientsDieseases PatientsDieseases { get; set; }
    }
}
