//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KSR_WardEntities : DbContext
    {
        public KSR_WardEntities()
            : base("name=KSR_WardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DirectorMessages> DirectorMessages { get; set; }
        public DbSet<Examinations> Examinations { get; set; }
        public DbSet<Patients> Patients { get; set; }
        public DbSet<PatientsDieseases> PatientsDieseases { get; set; }
    }
}
